### ISSUE TITLE
未知原因闪退

### ISSUE THREAD

**Issue by shanjb0221** [robertying/learnX#1040]
启动时遇到偶发性闪退问题，不清楚如何复现

应用版本：v14.1.2 (build 612566411)

设备信息：Mi 10 Ultra，MIUI 13.0.5，Android 12

trace：

```
com.facebook.react.common.JavascriptException: Invariant Violation: Failed to call into JavaScript module method RCTEventEmitter.receiveTouches(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, HMRClient, AppRegistry.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes, stack:
invariant@1:68328
__callFunction@1:73580
anonymous@1:72022
__guard@1:72972
callFunctionReturnFlushedQueue@1:71980

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:102)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:130)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:142)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:52)
	at java.lang.Thread.run(Thread.java:920)
```

**Comment by shanjb0221** [comment]
> 我在崩溃记录里也看到好多这种报错，但是我没法理解哪里出错了。感觉确实没法复现，是启动时可能正常也可能闪退嘛？

是的，绝大多数情况下都正常启动。只出现过一次闪退

**Comment by robertying** [comment]
过几天更新 RN 版本，再看看效果。

**Comment by robertying** [comment]
请测试 v14.2.0 是否还会间歇性闪退。

**Comment by Siyuanwww** [comment]
> 请测试 v14.2.0 是否还会间歇性闪退。

目前在 Xiaomi 12S Pro 上仍有启动时间歇性闪退

**Comment by robertying** [comment]
这一周在 v14.9.3+ 上没有观察到类似的崩溃了。希望彻底修复了。
